name       : qt5-docs
version    : 5.15.10
release    : 28
source     :
    - https://download.qt.io/official_releases/qt/5.15/5.15.10/single/qt-everywhere-opensource-src-5.15.10.tar.xz : b545cb83c60934adc9a6bbd27e2af79e5013de77d46f5b9f5bb2a3c762bf55ca
license    : GFDL-1.3-only
component  : programming.tools
summary    : Qt5 framework documentation
description: |
    qt5-docs provides the documentation for the whole Qt5 framework in a single package. Example code instead can be found in "demos" subpackages, e.g. "qt5-base-demos".
replaces   :
    - qt5-base-docs
patterns   :
    - / # libsplit:no is ignored for .qch files. A pattern is needed.
builddeps  :
    - pkgconfig(Qt5UiTools)
setup      : |
    # Yes Qt5, you should use prebuilt tools.
    ln -s /usr/bin qttools
    ln -s /usr/bin/{moc,rcc,uic,qmake} qtbase/bin

    %patch -d qtbase -p1 < $pkgfiles/no-qmake.patch

    ./configure                    \
        -confirm-license           \
        -docdir /usr/share/doc/qt5 \
        -nomake examples           \
        -nomake tests              \
        -opensource                \
        -prefix /usr               \
        -release
build      : |
    %make docs
install    : |
    %make install_docs INSTALL_ROOT=$installdir
