name       : qt5-docs
version    : 5.15.5
release    : 24
source     :
    - https://download.qt.io/official_releases/qt/5.15/5.15.5/single/qt-everywhere-opensource-src-5.15.5.tar.xz : 5a97827bdf9fd515f43bc7651defaf64fecb7a55e051c79b8f80510d0e990f06
license    : GFDL-1.3-only
component  : programming.tools
summary    : Qt5 framework documentation
description: |
    qt5-docs provides the documentation for the whole Qt5 framework in a single package. Example code instead can be found in "demos" subpackages, e.g. "qt5-base-demos".
replaces   :
    - qt5-base-docs
patterns   :
    - / # libsplit:no is ignored for .qch files. A pattern is needed.
builddeps  :
    - pkgconfig(Qt5UiTools)
setup      : |
    ./configure                    \
        -confirm-license           \
        -docdir /usr/share/doc/qt5 \
        -nomake examples           \
        -nomake tests              \
        -opensource                \
        -prefix /usr               \
        -release

    # Yes Qt5, you should use prebuilt tools.
    ln -s /usr/bin qttools
    ln -s /usr/bin/{moc,rcc,uic} qtbase/bin
build      : |
    %make qmake_all
    %make docs
install    : |
    %make install_docs INSTALL_ROOT=$installdir
